UC_TOOLS_HOST_ELF := \
	$(UC_TOOLS)/linux/test_pram.dynamic.host.elf \
	$(UC_TOOLS)/linux/packet_bridge_main.dynamic.host.elf \
	$(UC_TOOLS)/linux/la_dmx.dynamic.host.elf \
	$(UC_TOOLS)/linux/vcd.dynamic.host.elf \
	$(UC_TOOLS)/linux/gdbstub_connect.dynamic.host.elf \
	$(UC_TOOLS)/linux/gdbstub_proxy.dynamic.hostdbg.elf \
	$(UC_TOOLS)/linux/gdbstub_lua51.dynamic.host.so \
	$(UC_TOOLS)/linux/flashdump_info.dynamic.hostdbg.elf \
	$(UC_TOOLS)/linux/vcd.dynamic.host.elf \
	$(UC_TOOLS)/linux/chop.dynamic.host.elf \
	$(UC_TOOLS)/linux/logic2_csv.dynamic.host.elf \
	$(UC_TOOLS)/linux/logic2.dynamic.host.elf \
	$(UC_TOOLS)/linux/rle_enc.dynamic.host.elf \
	$(UC_TOOLS)/linux/rle_dec.dynamic.host.elf \
	$(UC_TOOLS)/linux/log_parse_lua51.dynamic.host.so \
	$(UC_TOOLS)/linux/test_log_parse_index.dynamic.host.elf \
	$(UC_TOOLS)/linux/sha1sum.dynamic.host.elf \
	$(UC_TOOLS)/linux/test_sg_rle.dynamic.host.elf \
	$(UC_TOOLS)/linux/http_panel.dynamic.host.elf \
	$(UC_TOOLS)/linux/webserver_lua51.dynamic.host.so \
	$(UC_TOOLS)/linux/test_la.dynamic.host.elf \
	$(UC_TOOLS)/linux/ilog_browser.dynamic.host.elf \
	$(UC_TOOLS)/linux/test_userfaultfd.dynamic.host.elf \
	$(UC_TOOLS)/linux/xor_tee.dynamic.host.elf \
	$(UC_TOOLS)/linux/sqlite3_lua51.dynamic.host.so \
	$(UC_TOOLS)/linux/sqlite3_logparse.dynamic.host.so \
	$(UC_TOOLS)/linux/sqlite3_ilog.dynamic.host.so \
	$(UC_TOOLS)/linux/sqlite3_fs.dynamic.host.so \
	$(UC_TOOLS)/linux/sqlite3_csv.dynamic.host.so \
	$(UC_TOOLS)/linux/seek_hole.dynamic.host.elf \
	$(UC_TOOLS)/linux/tether_udp.dynamic.host.elf \
	$(UC_TOOLS)/linux/test_dir_traverse.dynamic.host.elf \
	$(UC_TOOLS)/linux/leftshift.dynamic.host.elf \
	$(UC_TOOLS)/linux/test_arena.dynamic.host.elf \
	$(UC_TOOLS)/linux/test_dlist.dynamic.host.elf \
	$(UC_TOOLS)/linux/test_lru.dynamic.host.elf \
