#!/bin/sh

# Generate the linker script.  The main reason to do it
# programatically is that INCLUDE doesn't work with out-of-tree
# builds.  So just flatten it.

[ -z "$MAIN_LD" ] && MAIN_LD=$(dirname $0)/stm32f1.ld

cat <<EOF

/* GENERATED BY $(readlink -f $0) */

/* Define memory regions. */
MEMORY
{
/* ORIGINAL
	rom (rx)  : ORIGIN = 0x08000000, LENGTH = 64K
	ram (rwx) : ORIGIN = 0x20000000, LENGTH = 20K


/* BOOTLOADER / HOST  */
	rom (rx)  : ORIGIN = 0x08000000, LENGTH = 0x2800
	ram (rwx) : ORIGIN = 0x20000000, LENGTH = 0x2000

}

/* Define the entry point of the output file. */
ENTRY (reset_handler)

/* Include the common ld script. */

$(cat $MAIN_LD)

EOF

