#ifndef SDIO_CMD_H
#define SDIO_CMD_H

// see Simplified_SDIO_Card_Spec.pdf page 59, Appendix A.
#define SDIO_CMD_GO_IDLE_STATE 0
#define SDIO_CMD_ALL_SEND_CID 2
#define SDIO_CMD_SEND_RELATIVE_ADDRESS 3
#define SDIO_CMD_IO_SEND_OP_COND 5
#define SDIO_CMD_SWITCH_FUNC 6
#define SDIO_CMD_SELECT 7
#define SDIO_CMD_SEND_IF_COND 8
#define SDIO_CMD_SEND_CSD 9
#define SDIO_CMD_STOP_TRANSMISSION 12
#define SDIO_CMD_SET_BLOCKLEN 16
#define SDIO_CMD_READ_SINGLE_BLOCK 17
#define SDIO_CMD_WRITE_SINGLE_BLOCK 24
#define SDIO_CMD_WRITE_MULTIPLE_BLOCK 25
#define SDIO_CMD_ERASE_WR_BLK_START_ADDR 32
#define SDIO_CMD_ERASE_WR_BLK_END_ADDR 33
#define SDIO_CMD_ERASE 38
#define SDIO_CMD_SD_APP_OP_COND 41
#define SDIO_CMD_APP_CMD 55

#define SDIO_ACMD_SEND_STATUS 13
#define SDIO_ACMD_SEND_SCR 51
#define SDIO_ACMD_SET_WR_BLK_ERASE_COUNT 23

#endif // SDIO_CMD_H
