#!/bin/bash

# Generate the linker script for binary data storage.  The main reason
# to do it programatically is that INCLUDE doesn't work with
# out-of-tree builds.  So just flatten it.

ADDR=$1

[ -z "$ADDR" ] && ADDR=0x8008000
# echo "ADDR=$ADDR" >&2

cat <<EOF

/* GENERATED BY $(readlink -f $0) */

SECTIONS {
        /* Date store block. Can be loaded independently of app. */
        .data $ADDR : { 
                KEEP (*(.data))
                . = ALIGN(4);
        }
}

PROVIDE(_data = $ADDR);

EOF

