#!/bin/bash

# Generate the linker script.  The main reason to do it
# programatically is that INCLUDE doesn't work with out-of-tree
# builds.  So just flatten it.

[ -z "$MAIN_LD" ] && MAIN_LD=$(dirname $0)/stm32f1.ld.sh

cat <<EOF

/* GENERATED BY $(readlink -f $0) */

MEMORY /* STM32F103x8 */
{
	rom (rx)  : ORIGIN = 0x08003000, LENGTH = 0xD000 /* 64kB total */
	ram (rwx) : ORIGIN = 0x20002000, LENGTH = 0x3000 /* 20kB total */
}

PROVIDE(_flash_top = 0x08010000);

/* This is to keep the linker happy.  main() is not used. */
PROVIDE(main = 0);

/* Fake entry point.  Apps are started manually through gdb RSP 
PROVIDE (_fake_reset_handler = 0);
ENTRY (_fake_reset_handler); */

ENTRY (reset_handler);


/* BEGIN: Include the common ld script. */

$($MAIN_LD)

/* END: Include the common ld script. */  

/* FIXME: Can't put this in the bootloader.  Is it ok to sit here
after the .config and .mem.* sections? */

SECTIONS {
	/* _eflash:         first free block in Flash memory after code.
	   _flash_bin_endx: end of firmware binary */
 	.flash_pad : {
		_flash_bin_endx = . ;     
		. = ALIGN(1024);
		_eflash = . ;     
 	} >rom

        /* If there is a .control section, then reserve a control
           block at _eflash that can later be patched by objcopy
           --update-section.  This is used e.g. by
           patch-control-block.sh to store CRC data in the .elf, which
           can only be computed in a second pass after linking has
           finished. */

        .control : {
		_control = . ;
                KEEP (*(.control)) ;
		. = ALIGN(1024);
        } >rom
}

EOF

