[package]
name = "dataflow_lua51_rs"
version = "0.1.0"
authors = ["Author Name <tom@zwizwa.be>"]

[lib]
# Create a Lua-loadable .so dynamic library.
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.10.3", features = ["lua51", "module"] }


