#!/bin/sh

# Note that this used to be for 256k Flash STM32F103, but the only
# application that uses the 256a/b partition config at this time
# (2025/9) is always running on Geehy APM32E103RET6 which has 512k
# Flash and 128k SRAM.  The Flash partitioning scheme only uses 256k
# of the Flash for two 128k application partitions, but the RAM is
# fully used.  The second 256k of the Flash is reserved for debugging.

# For use with dual-partition firmware on 
#
# bl + tramp:  0x08000000 - 0x08004000
# partition a: 0x08004000 - 0x08022000 (both have 0x800 config + rest is firmware)
# partition b: 0x08022000 - 0x08040000


[ -z "$MAIN_LD" ] && MAIN_LD=$(dirname $0)/stm32f1.ld.sh
[ -z "$END_LD" ]  && END_LD=$(dirname $0)/stm32f1_end.ld.sh 

case $(basename $0) in
    256b.f103.ld.sh)
        CONFIG=0x08022000
        ORIGIN=0x08022800
        # LENGTH=0x1D000 # From ORIGIN to end of Flash
        LENGTH=0x1C000 # Leave room for 2k log dump
        ;;
    *)
        CONFIG=0x08004000
        ORIGIN=0x08004800
        LENGTH=0x1D800 # From ORIGIN to beginning of partition B
        ;;
esac

FLASH_BLOCK_SIZE=2048

export CONFIG
export ORIGIN
export FLASH_BLOCK_SIZE

# echo ORIGIN=$ORIGIN >&2

cat <<EOF

/* About rom LENGTH:
   This is the space between ORIGIN=$ORIGIN and the start of the next partition or the end of Flash.
   Note that the .control block is included in LENGTH (see e.g. stm32f1_end.ld.sh).

*/

/* GENERATED BY $(readlink -f $0) */

MEMORY /* STM32F103x8 */
{
        rom (rx)  : ORIGIN = $ORIGIN, LENGTH = $LENGTH
	ram (rwx) : ORIGIN = 0x20002000, LENGTH = 0x1E000 /* 128kB total */
}

/* Most stm32f103 in the wild have 128k */
PROVIDE(_flash_top = 0x08020000);

/* This is to keep the linker happy.  main() is not used. */
PROVIDE(main = 0);

/* Fake entry point.  Apps are started manually through gdb RSP 
PROVIDE (_fake_reset_handler = 0);
ENTRY (_fake_reset_handler); */

ENTRY (reset_handler);


/* BEGIN: $MAIN_LD */

$($MAIN_LD)

/* END: $MAIN_LD */


/* BEGIN: $END_LD */

$($END_LD)

/* END: $END_LD */

EOF

