#include <stdint.h>
#include "macros.h"

#define add(a,b) ((a)+(b))
typedef uintptr_t T;

void send(uint32_t val) {}

// Generated by test_scm.lua from test_csp.sm
// See also test_smc_csp.conf
#include "test_co.sm.c"

int main(int argc, char **argv) {
    struct state s = {};
    testmod(&s);
    return 0;
}
