/* FIXME: Just a stub.

   The idea here is to create a test for a real-world problem:
   handling UART RX/TX interrupts.

   (define (forwarder)
     (wait-rx)
     (let* ((byte (read-rx-reg)))
       (if (tx-ready?)
         (write-tx-reg! byte)
         (begin
           (wait-tx)
           (write-tx-reg! byte))))
     (forwarder))

   Currently split between two approach: keep it "simple" by only
   allowing uC interrupts to be events, or keeping it more general to
   both represent interrupts directly + also have arbitrary inter-task
   events (e.g. for software timer).

*/

#include <stdint.h>
#include "macros.h"
// Context
#define SM_READ(s, chan, label, arg) \
    ({ return &&label; label: arg; })
#define add(a,b) ((a)+(b))
typedef uintptr_t T;

void send(uint32_t val) {}

// Generated by test_scm.lua from test_csp.sm
// See also test_smc_csp.conf
#include "test_csp.sm.c"

int main(int argc, char **argv) {
    struct state s = {};
    testmod(&s, NULL, 0);
    return 0;
}
