#include <stdint.h>
#include "macros.h"
// Context
typedef struct {
    uint32_t e[100];
} state_t;
#define READ(chan) 123
#define add(a,b) ((a)+(b))
typedef uint32_t T;

void send(uint32_t val) {}

// Generated by test_scm.lua from test.scm
#include "mod_test_scm.c"
int main(int argc, char **argv) {
    return 0;
}
