#include <stdint.h>
#include "macros.h"
// Context
#define SM_READ(s, chan, label) 123
#define add(a,b) ((a)+(b))
typedef uint32_t T;

void send(uint32_t val) {}

// Generated by test_scm.lua from test.sm
// See also test_scm.conf
#include "test.sm.c"

int main(int argc, char **argv) {
    return 0;
}
