#include <stdint.h>
#include "macros.h"

#define add(a,b) ((a)+(b))
typedef uintptr_t T;

void send(uint32_t val) {}

// Generated by test_scm.lua from *.sm
// See also test_smc_co.conf with dep spec.
#include "test_co.sm.c"
#include "test1.sm.c"

void run_test_co(void) {
    struct test_co_state s = {};
    for (int i=0; i<10; i++) {
        T rv = test_co(&s, 0);
        LOG("%d -> %d\n", i, rv);
        ASSERT(rv == i + 1);
    }
}
void run_test1(void) {
    struct test1_state s = {};
    for (int i=0; i<10; i++) {
        T rv = test1(&s, 0);
        LOG("%d -> %d\n", i, rv);
    }
}

int main(int argc, char **argv) {
    run_test1();
    //run_test_co();
    return 0;
}

