#include <stdint.h>
#include "macros.h"
// Context
typedef struct {
    uint32_t e[100];
} state_t;
#define SM_READ(s, chan) 123
#define add(a,b) ((a)+(b))
typedef uint32_t T;

void send(uint32_t val) {}

// Generated by test_scm.lua from test.scm
// See also test_scm.pterm
#include "mod_test_smc.c"

int main(int argc, char **argv) {
    return 0;
}
