#include <stdint.h>
#include "macros.h"
// Context
#define SM_READ(s, chan, label) ({ return 456; arg; })
#define add(a,b) ((a)+(b))
typedef uint32_t T;
// Dummy, not used
struct csp_task {};
struct csp_evt {};


void send(uint32_t val) {}

// Generated by test_scm.lua from test.sm
// See also test_scm.conf
#include "test.sm.c"

int main(int argc, char **argv) {
    return 0;
}
