// Originally generated by https://claude.ai/chat/aa694c0d-4275-4d2d-a99b-4a662d6467ae

// Reviewed and commented.  This is my first real shader.  I've added
// some beginner remarks.

// Don't bother with medium precision until testable.
// precision mediump float;
precision highp float;

// Character grid and font are stored in textures.  Note that
// texture2D() always returns a vec4.  Results are padded.

uniform sampler2D uCells;   // 80x25, character + attr per texel
uniform sampler2D uFont;    // glyph atlas
uniform vec2 uDims;         // e.g. (80, 25) for VGA
uniform vec2 uAtlasGlyphs;  // glyphs per row/col in atlas, e.g. (16, 16)


void main() {
  vec2 screenUV = gl_FragCoord.xy / vec2(80.0*8.0, 25.0*16.0);

  // which cell are we in, and where inside that cell (0..1)
  vec2 cellF   = screenUV * uDims;
  vec2 cell    = floor(cellF);
  vec2 inCell  = fract(cellF);          // position within the 8x16 glyph

  // look up the character code for this cell
  vec4 c       = texture2D(uCells, (cell + 0.5) / uDims);
  float code   = floor(c.r * 255.0 + 0.5);
  
  // map code -> position in the atlas
  vec2 glyph   = vec2(mod(code, uAtlasGlyphs.x), floor(code / uAtlasGlyphs.x));
  vec2 atlasUV = (glyph + inCell) / uAtlasGlyphs;
  
  vec4 texel   = texture2D(uFont, atlasUV);
  gl_FragColor = texel;   // + attribute->fg/bg coloring here
}

