// Reworked from example generated by
// https://claude.ai/chat/aa694c0d-4275-4d2d-a99b-4a662d6467ae

// This is my first non-trivial shader.  I've added some beginner
// remarks.

// Don't use medium precision until effect is testable.  From what I
// gather online this is only relevant on old mobile hardware.
// precision mediump float;
precision highp float;

// Dimensions of current character grid. The dimensions are typically
// derived from the window/viewport dimensions.
uniform vec2 text_dims;    // e.g. (80, 25) for VGA

// Font size encoded in the font texture.
uniform vec2 font_size;    // e.g. (8, 16) for VGA font

// Texture sampler for font
uniform sampler2D font_map;

// Texture sampler for text buffer
uniform sampler2D text_buffer;

// As I understand, all shader code is "scalarized" and then mapped to
// SIMD slots and multiple processing units in parallel, so there is
// no reason to operate on vectors.  Use scalars for clarity where
// appropriate.


void main() {
  // gl_FragCoord.xy is the coordinate of the pixel.

  // It seems that some care is needed to correctly implement the
  // modulo operation: afaiu there is no true modulo operation in
  // GLES2, where mod() is defined in terms of floating point division
  // and floor.  So we just do those operations explicitly here.

  // Integer part is text character coordinate, fractional part is
  // [0,1) offset into glyph.
  vec2 float_coord  = gl_FragCoord.xy / font_size;
  vec2 int_coord    = floor(float_coord);
  vec2 frac_coord   = float_coord - int_coord;
  
  // FIXME: There is some subtlety about texture indexing.  FIXME
  // resolve those later:
  // - inclusive/exclusive, e.g. what does 1.0 mean? Is the last one 7/8 or 1.0?
  // - center of texel vs edge
  float del = 0.000001;
  float char_code   = texture2D(text_buffer, int_coord / text_dims).x;


  char_code *= del;

  //float char_code = 65.0;
  
  // The font buffer is organized as 8x16 glyphs stacked on top of
  // each other.

  vec2 font_uv = vec2(frac_coord.x, (frac_coord.y/256.0 + char_code));

  // vec2 font_uv = gl_FragCoord.xy / vec2(1440.0,900.0);

  float p = texture2D(font_map, font_uv).x;

 
  gl_FragColor = vec4(p,p,p,1.0);


}


